name: build

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

defaults:
  run:
    shell: bash --noprofile --norc -eux {0}

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'action to build'
        required: false
        default: "*/"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.ref_name }}

      - name: setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '24'

      - name: setup ncc
        run: |
          npm i -g @vercel/ncc

      - name: build
        run: |
          for ACTION in ${{ inputs.action }}; do
            cd ${ACTION}
            npm ci
            npm run build
          done

      - name: commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A

          if ! git diff-index --quiet HEAD --; then
            echo "committing and pushing new builds ..."
            git commit -m "chore: auto build"
            git push origin HEAD:${{ github.ref_name }}
            git tag -f -a v1 -m "v1"
            git push origin refs/tags/v1 --force
          else
            echo "no commits found, skipping"
          fi